name: Run Daily to Trigger Deployment
on:
  schedule:
#  - cron: '0 0 * * *'   # Runs everyday at midnight
    - cron: '*/5 * * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js environment
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Install dependencies
      run: npm install
    - name: Run app
      run: node index.js
    # Trigger deploy webhook

    - name: HTTP Request Action
      uses: fjogeleit/http-request-action@v1.14.0
      with:
        url: "https://api.render.com/deploy/srv-cgn8en7dvk4k010hvb4g?key=plTdXCsfPT0"
        method: POST

