name: Daily Node.js App
on:
  schedule:
#     - cron: '0 0 * * *'   # Runs everyday at midnight
  - cron: '*/10 * * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js environment
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Install dependencies
      run: npm install
    - name: Run app
      run: node index.js
    - name: Start server
      run: node server.js
